### ISSUE TITLE
JMS client cannot receive JMS event from VSD

### ISSUE THREAD

**Issue by yuanji-xuan** [nuagenetworks/jmsclient#1]
Hi Nuage experts,
Sorry for disturbing, I’m coming from HPE China Team, we are also integrating with Nuage JMS.
 
We faced an issue that remote JMS client cannot receive Nuage JMS server’s events.
It seems a connectivity problem, since we can connect to the JMS server and get JMS events locally but not remotely.
Would you please give us some suggestions?
Thanks a lot in advance!

-------------------------------------
1.	Issue brief: (Snapshots are in the attached file)
            remote JMS client cannot receive Nuage JMS server’s event

2.	Version& IP Info:
Nuage Version: V4.0R10
JMS client version: JMS Client for VSD 4.0

3.	Issue details**( 3.3 and 3.5 maybe the probable cause???)**:
3.1	 JMS Client& Server can ping each other. And From JMS Client node the “telnet VSD_IP 4447” is OK.
3.2	 Firewalls are closed for both JMS client& server nodes.
**3.3	 After check the port status on JMS client& server nodes, the TCP connection is established. 
And tcpdump -n -nn host 10.34.46.14 seems that the VSD can push the packets with size 21
All the packets' size is 21, really weird.**
3.4	 But on JMS Client server, after execute the command “./runjmsclient.sh 10.34.41.203”, The log shows that JMS client cannot get the event messages remotely.
(But execute the same command on VSD JMS server side, it can get detail JMS events)
 
**3.5 Is there any configuration on JMS server side to control whether allow remote connection or not? 
i.e, JMS server in Nuage is a JBoss, so the configuration should be done properly in this JBoss to accept remote connections. I think this configuration is set by default, but this is a question I want to confirm with Nuage experts: how to check whether the JMS configuration is correct?
       /opt/vsd/jboss/standalone/configuration/standalone-full-ha.xml**

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549
[JMS client issue .zip](https://github.com/nuagenetworks/jmsclient/files/1475397/JMS.client.issue.zip)

**Comment by yuanji-xuan** [comment]
@ssudharsan23
It'll be very appreciated if you can have a look into this case. 
Thanks  in a million in advance!

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549
JMS client issue .zip

**Comment by ssudharsan23** [comment]
Hi,
Can you please share your jmsclient.zip file and logs with us?
Can you confirm if port 4447, 5445 and 5446 are open on the vsd.
Please share your iptable rules as well.

**Comment by yuanji-xuan** [comment]
@ssudharsan23
Thanks  a lot for your answer.

1. We are using this jmsclient which is downloaded from https://github.com/nuagenetworks/jmsclient/releases/download/R4.0/jmsclient-1.0.5-dist.zip
2. jmsclient.log is in the attachment:
[jmsclient.zip](https://github.com/nuagenetworks/jmsclient/files/1477068/jmsclient.zip)

3. We have stopped the iptables on both VSD JMS server & remote JMS client node.

4. Port Status on JMS Server(10.34.41.203), result for netstat -ano|grep -E "4447|5445|5446"  :

```
> 	[root@vsd log]# netstat -ano|grep -E "4447|5445|5446"
> 	tcp        0      0 0.0.0.0:4447            0.0.0.0:*               LISTEN      off (0.00/0/0)
> 	tcp        0      0 10.34.41.203:5445       0.0.0.0:*               LISTEN      off (0.00/0/0)
> 	tcp        0      0 10.34.41.203:4447       10.34.46.14:61763       ESTABLISHED off (0.00/0/0)
> 	tcp        0      0 127.0.0.1:59515         127.0.0.1:4447          ESTABLISHED off (0.00/0/0)
> 	tcp        0      0 10.34.41.203:5445       10.34.41.203:53306      ESTABLISHED keepalive (4941.17/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.41.203:53542      ESTABLISHED on (0.20/0/0)
> 	tcp        0      0 10.34.41.203:53600      10.34.41.203:5445       ESTABLISHED keepalive (5072.25/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.41.203:53600      ESTABLISHED on (0.20/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.41.203:53602      ESTABLISHED on (0.20/0/0)
> 	tcp        0      0 10.34.41.203:53542      10.34.41.203:5445       ESTABLISHED keepalive (5072.25/0/0)
> 	tcp        0      0 127.0.0.1:4447          127.0.0.1:59515         ESTABLISHED off (0.00/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.46.14:31035       ESTABLISHED on (0.20/0/0)
> 	tcp        0      0 10.34.41.203:53602      10.34.41.203:5445       ESTABLISHED keepalive (5072.24/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.41.203:53604      ESTABLISHED on (0.20/0/0)
> 	tcp        0      0 10.34.41.203:53306      10.34.41.203:5445       ESTABLISHED keepalive (4941.17/0/0)
> 	tcp        0      0 10.34.41.203:53604      10.34.41.203:5445       ESTABLISHED keepalive (5072.24/0/0)
> 	
> 	[root@vsd log]# netstat -ano|grep -E "4447|5445|5446"|grep 10.34.46.14
> 	tcp        0      0 10.34.41.203:4447       10.34.46.14:61763       ESTABLISHED off (0.00/0/0)
> 	tcp        0     21 10.34.41.203:5445       10.34.46.14:31035       ESTABLISHED on (0.20/0/0)
> 
```

5. Port Status on JMS Client(10.34.46.14), result for netstat -ano|grep -E "4447|5445|5446"  :

```
> 	[root@sddev log]# netstat -ano|grep -E "4447|5445|5446"
> 	tcp        0      0 ::ffff:10.34.46.14:31035    ::ffff:10.34.41.203:5445    ESTABLISHED keepalive (6976.09/0/0)
> 	tcp        0      0 ::ffff:10.34.46.14:61763    ::ffff:10.34.41.203:4447    ESTABLISHED off (0.00/0/0)
> 
```

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549

**Comment by yuanji-xuan** [comment]
@ssudharsan23 

**Another very weird thing is ,all the packets' length is 21 between JMS Client& JMS Server.**
below is the packet capture command result on JMS Server with filters jmsclientIP& 3 ports: 
**tcpdump -n -nn host 10.34.46.14 and port \( 4447 or 5445 or 5446 \)**

```
> 	[root@vsd log]# tcpdump -n -nn host 10.34.46.14 and port \( 4447 or 5445 or 5446 \) -c 10
> 	tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
> 	listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
> 	01:12:59.162653 IP 10.34.46.14.31035 > 10.34.41.203.5445: Flags [P.], seq 634287352:634287373, ack 2840512630, win 374, options [nop,nop,TS val 1448674389 ecr 46407580], length 21
> 	01:12:59.162720 IP 10.34.41.203.5445 > 10.34.46.14.31035: Flags [P.], seq 1:22, ack 21, win 235, options [nop,nop,TS val 46407590 ecr 1448674389], length 21
> 	01:12:59.172788 IP 10.34.46.14.31035 > 10.34.41.203.5445: Flags [P.], seq 21:42, ack 22, win 374, options [nop,nop,TS val 1448674400 ecr 46407590], length 21
> 	01:12:59.172955 IP 10.34.41.203.5445 > 10.34.46.14.31035: Flags [P.], seq 22:43, ack 42, win 235, options [nop,nop,TS val 46407600 ecr 1448674400], length 21
> 	01:12:59.182891 IP 10.34.46.14.31035 > 10.34.41.203.5445: Flags [P.], seq 42:63, ack 43, win 374, options [nop,nop,TS val 1448674410 ecr 46407600], length 21
> 	01:12:59.183006 IP 10.34.41.203.5445 > 10.34.46.14.31035: Flags [P.], seq 43:64, ack 63, win 235, options [nop,nop,TS val 46407610 ecr 1448674410], length 21
> 	01:12:59.192980 IP 10.34.46.14.31035 > 10.34.41.203.5445: Flags [P.], seq 63:84, ack 64, win 374, options [nop,nop,TS val 1448674420 ecr 46407610], length 21
> 	01:12:59.193067 IP 10.34.41.203.5445 > 10.34.46.14.31035: Flags [P.], seq 64:85, ack 84, win 235, options [nop,nop,TS val 46407620 ecr 1448674420], length 21
> 	01:12:59.203265 IP 10.34.46.14.31035 > 10.34.41.203.5445: Flags [P.], seq 84:105, ack 85, win 374, options [nop,nop,TS val 1448674430 ecr 46407620], length 21
> 	01:12:59.203437 IP 10.34.41.203.5445 > 10.34.46.14.31035: Flags [P.], seq 85:106, ack 105, win 235, options [nop,nop,TS val 46407630 ecr 1448674430], length 21
> 	10 packets captured
> 	12 packets received by filter
> 	0 packets dropped by kernel
```
below is the packet capture command on JMS Server with filters jmsclientIP& 3 ports: 

> `tcpdump -n -nn host 10.34.46.14 and port \( 4447 or 5445 or 5446 \) -w ./jms_tcpdump.cap`

also attached the dump result into file: 

> [jms_tcpdump.zip](https://github.com/nuagenetworks/jmsclient/files/1477210/jms_tcpdump.zip)

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549

**Comment by yuanji-xuan** [comment]
@ssudharsan23

After open debug by "./setLogLevel.sh -l DEBUG all ", the jmsclient.log is as bleow:
(Also attached the file: [jmsclient.zip](https://github.com/nuagenetworks/jmsclient/files/1480902/jmsclient.zip))

```
> 16-Nov-2017 18:41:17,166 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) >>>> Starting JMSTopicClient <<<<
> 16-Nov-2017 18:41:17,166 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) ===============================================
> 16-Nov-2017 18:41:17,166 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * using following values: 
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * JMS Server list: 10.34.41.203
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * JMS port: 4447
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * property.file: /tmp/xyj/jmsclient-1.0.5/jmsclient.properties
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * log.file.path: /tmp/xyj/jmsclient-1.0.5/log
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * log.file: jmsclient.log
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * client.id: 016d4995-9913-428c-bd04-73932896426c
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) * client.name: null
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) ===============================================
> 16-Nov-2017 18:41:17,167 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Connection: remote://10.34.41.203:4447
> 16-Nov-2017 18:41:17,167 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Topic: jms/topic/CNAMessages
> 16-Nov-2017 18:41:17,167 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) User: jmsclient@csp
> 16-Nov-2017 18:41:17,167 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Establishing JNDI Context: {java.naming.provider.url=remote://10.34.41.203:4447, java.naming.factory.initial=org.jboss.naming.remote.client.InitialContextFactory, java.naming.factory.url.pkgs=org.jboss.naming:org.jnp.interfaces}
> 16-Nov-2017 18:41:17,184 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.Log4jLoggerProvider
> 16-Nov-2017 18:41:17,200 DEBUG [org.jboss.naming.remote.client.InitialContextFactory] (main) Looking for jboss-naming-client.properties using classloader sun.misc.Launcher$AppClassLoader@55f96302
> 16-Nov-2017 18:41:17,201 DEBUG [org.jboss.naming.remote.client.InitialContextFactory] (main) jboss.naming.client.endpoint.create.options. has the following options {}
> 16-Nov-2017 18:41:17,202 DEBUG [org.jboss.naming.remote.client.InitialContextFactory] (main) jboss.naming.client.remote.connectionprovider.create.options. has the following options {}
> 16-Nov-2017 18:41:17,209 INFO  [org.xnio] (main) XNIO Version 3.0.7.GA
> 16-Nov-2017 18:41:17,216 INFO  [org.xnio.nio] (main) XNIO NIO Implementation Version 3.0.7.GA
> 16-Nov-2017 18:41:17,225 INFO  [org.jboss.remoting] (main) JBoss Remoting version 3.2.14.GA
> 16-Nov-2017 18:41:17,241 DEBUG [org.xnio.nio] (Remoting "config-based-naming-client-endpoint" read-1) Started channel thread 'Remoting "config-based-naming-client-endpoint" read-1', selector sun.nio.ch.EPollSelectorImpl@496d6039
> 16-Nov-2017 18:41:17,243 DEBUG [org.xnio.nio] (Remoting "config-based-naming-client-endpoint" write-1) Started channel thread 'Remoting "config-based-naming-client-endpoint" write-1', selector sun.nio.ch.EPollSelectorImpl@28612c85
> 16-Nov-2017 18:41:17,309 DEBUG [org.jboss.naming.remote.client.InitialContextFactory] (main) jboss.naming.client.connect.options. has the following options {}
> 16-Nov-2017 18:41:17,669 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) topic name from provider: jms/topic/CNAMessages, topicObject: HornetQTopic[CNAMessages]
> 16-Nov-2017 18:41:17,669 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) creating JMS connection
> 16-Nov-2017 18:41:17,683 DEBUG [org.hornetq.core.client] (main) Trying reconnection attempt 0/1
> 16-Nov-2017 18:41:17,687 DEBUG [org.hornetq.core.client] (main) Trying to connect with connector = org.hornetq.core.remoting.impl.netty.NettyConnectorFactory@4b553d26, parameters = {port=5445, host=10.34.41.203} connector = NettyConnector [host=10.34.41.203, port=5445, httpEnabled=false, useServlet=false, servletPath=/messaging/HornetQServlet, sslEnabled=false, useNio=false]
> 16-Nov-2017 18:41:17,708 DEBUG [org.hornetq.core.client] (main) Started Netty Connector version 3.6.2.Final-c0d783c
> 16-Nov-2017 18:41:17,708 DEBUG [org.hornetq.core.client] (main) Trying to connect at the main server using connector :TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203
> 16-Nov-2017 18:41:17,708 DEBUG [org.hornetq.core.client] (main) Remote destination: /10.34.41.203:5445
> 16-Nov-2017 18:41:17,763 DEBUG [org.hornetq.core.client] (main) Reconnection successfull
**> 16-Nov-2017 18:41:17,768 DEBUG [org.hornetq.core.client] (Thread-1 (HornetQ-client-global-threads-525683462)) Node 37414f8a-c9ff-11e7-aa82-fddac2d8e48f going up, connector = Pair[a=TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203, b=null], isLast=true csf created at
> serverLocator=ServerLocatorImpl [initialConnectors=[TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203], discoveryGroupConfiguration=null]
> java.lang.Exception
> 	at org.hornetq.core.client.impl.ClientSessionFactoryImpl.<init>(ClientSessionFactoryImpl.java:197)
> 	at org.hornetq.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:808)
> 	at org.hornetq.jms.client.HornetQConnectionFactory.createConnectionInternal(HornetQConnectionFactory.java:583)
> 	at org.hornetq.jms.client.HornetQConnectionFactory.createConnection(HornetQConnectionFactory.java:107)
> 	at com.alu.cna.cloudmgmt.util.jms.AbstractJMSClient.connect(AbstractJMSClient.java:355)
> 	at com.alu.cna.cloudmgmt.util.jms.AbstractJMSClient.execute(AbstractJMSClient.java:130)
> 	at com.alu.cna.cloudmgmt.util.jms.JMSTopicClient.main(JMSTopicClient.java:40)
> 16-Nov-2017 18:41:17,770 DEBUG [org.hornetq.core.client] (Thread-1 (HornetQ-client-global-threads-525683462)) NodeUp ServerLocatorImpl [initialConnectors=[TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203], discoveryGroupConfiguration=null]::nodeID=37414f8a-c9ff-11e7-aa82-fddac2d8e48f, connectorPair=Pair[a=TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203, b=null]
> java.lang.Exception: trace
> 	at org.hornetq.core.client.impl.ServerLocatorImpl.notifyNodeUp(ServerLocatorImpl.java:1509)
> 	at org.hornetq.core.client.impl.ClientSessionFactoryImpl$Channel0Handler$1.run(ClientSessionFactoryImpl.java:1611)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 16-Nov-2017 18:41:17,771 DEBUG [org.hornetq.core.client] (Thread-1 (HornetQ-client-global-threads-525683462)) Topology@7586067a[owner=ServerLocatorImpl [initialConnectors=[TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203], discoveryGroupConfiguration=null]]::NewMemeberAdd nodeId=37414f8a-c9ff-11e7-aa82-fddac2d8e48f member = TopologyMember[name = null, connector=Pair[a=TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203, b=null]]
> java.lang.Exception: trace
> 	at org.hornetq.core.client.impl.Topology.updateMember(Topology.java:199)
> 	at org.hornetq.core.client.impl.ServerLocatorImpl.notifyNodeUp(ServerLocatorImpl.java:1514)
> 	at org.hornetq.core.client.impl.ClientSessionFactoryImpl$Channel0Handler$1.run(ClientSessionFactoryImpl.java:1611)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)**
> 16-Nov-2017 18:41:17,771 DEBUG [org.hornetq.core.client] (main) ClientSessionFactoryImpl received backup update for live/backup pair = TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203 / null but it didn't belong to TransportConfiguration(name=netty, factory=org-hornetq-core-remoting-impl-netty-NettyConnectorFactory) ?port=5445&host=10-34-41-203
> 16-Nov-2017 18:41:17,775 DEBUG [org.hornetq.utils] (main) using dummy address ffffffe5:6f:3a:ffffff82:ffffff9d:-100
> 16-Nov-2017 18:41:17,921 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) started JMS session
> 16-Nov-2017 18:41:17,921 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) starting JMS connection
> 16-Nov-2017 18:41:17,921 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) conn client id from JMS: 016d4995-9913-428c-bd04-73932896426c
> 16-Nov-2017 18:41:17,921 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Filter: 
> 16-Nov-2017 18:41:18,086 DEBUG [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Created non-durable subscriber
> 16-Nov-2017 18:41:18,087 INFO  [com.alu.cna.cloudmgmt.util.jms.JMSTopicClient] (main) Started connection...
```
Thanks& BRs
yuanji

**Comment by yuanji-xuan** [comment]
@ssudharsan23

We did further research on this case:

1. The tcp packets are sent normally from jms server node to jms client node
(Because after analyse the captured tcp packets in WireShark, we can see the detail events' content sent from jms server to jms client, whose size is > 21)

2. In JMSMessageHandler, we put some breakpoints on OnMessage& processMessage method , but it never stop. 
We don't know why the JMSMessageHandler not working, can you give us any suggestion here?

Is it related to version? i.e., OS, Java, VSD version?

> our jms client os is : RHEL 6.7
> our jms server(vsd) os is: RHEL 7.2
> 
> VSD version: v4.0R10
> 
> Java version on jms client: 1.8.0_111(build 1.8.0_111-b14)
> Java version on jms server(vsd):1.7.0_131 (build 1.7.0_131-b31)


Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549

**Comment by ssudharsan23** [comment]
Hi,

1. Can you capture tcp packets using wireshark on the jmsclient node. Just to ensure whether you receive packets on the jmsclient node.
2. Port 5050 is the Java debugger port for JMS client. Can you check if you are able to connect to it.

OS version or JAVA version or VSD version will not cause any issue since your JMS client is successfully connected to VSD server.

Thanks & Regards,
S.Sudharsan

**Comment by yuanji-xuan** [comment]
@ssudharsan23
Thanks a lot for your suggestions!

1. We can capture tcp packets in both client& server node, and can see the detail events content on jms client. 

2.  In the runjmsclient.sh, I just added a port 52002 for debug and I found the debugger can be triggered by the breakpoint in connect() method. This means the eclipse debugger can connect to the remote jmsclient.  
exec java $DEBUGOPT  **-Xdebug -Xrunjdwp:transport=dt_socket,address=52002,server=y,suspend=y** -cp $CP $systemProp com.alu.cna.cloudmgmt.util.jms.${mainClass} $otherArgs

**3. But the debugger  is never  triggered by the breakpoints in OnMessage& processMessage methods, it means these methods are not be executed. ** 

Do you have any suggestions on this? 
I think zg.qiu from nokia also contacted with you on this issue.  If possible can you connect to our environment to have a glance ? 

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549

**Comment by yuanji-xuan** [comment]
@ssudharsan23

We did another test, From the same client node , Using the same jmsclient to connect another test VSD(V4R10), we can see the event detail information in jmsclient.log.

So the probable cause should be in VSD itself. We will try to reinstall the VSD and do the tests again and keep you up-to-date:
1. Reinstall a new VSD and test JMSClient
2. If 1 is ok, then import the backup data and test the JMSClient

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549

**Comment by yuanji-xuan** [comment]
@ssudharsan23

The root cause has been found: the jms client & jms server connected to different NTP server, but the NTP servers are different and have different time settings. After change the NTP server, the remote jms client can receive jms events successfully.
Thanks a lot for your help!

Thanks& BRs
Xuan, Yuanji
HPE
Mail: Yuanji.xuan@hpe.com
Tel: +86 18601030549
